### ISSUE TITLE
Bug in tags

### ISSUE THREAD

**Issue by sasumaki** [UniversityOfHelsinkiCS/oodikone#1038]
current issue

1. create a tag
2. add this tag to a student via student table in population statistics
3. filter by that specific tag
4. student not showing up on the filtered population

For now this is not to be fixed.

~~Repro:~~
~~1) create new tag~~
~~2) add this tag to people~~
~~3) try to filter by this tag => tag not present in filter dropdown~~

**Comment by esakemp** [comment]
This is known and has to do with how population statistics page works. Currently the population data is only fetched once when the page is loaded so the new added tags won't be available in the fetched data. Even if you add tags to people that are shown in the filter dropdown, they won't be filtered since you need to update the population to get the new tag data. 

Maybe we should add update population button to the tag panel? Or add a whole separate page for managing student tags.
