### ISSUE TITLE
student statistics: studyright (ui?) fuckup in some cases

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone#2574]
see eg 014580736

in sis-oodikone

![image](https://user-images.githubusercontent.com/523235/106933097-37a3de80-6721-11eb-8d26-a67abb5c3c5b.png)

oodi-oodikone

![image](https://user-images.githubusercontent.com/523235/106933258-60c46f00-6721-11eb-883b-844caefc0cba.png)

**Comment by otahontas** [comment]
Partly fixed, but leaving this open, since following need to be checked:

- [ ] degrees are fetched for only some students, so current progam logic might not be the most working one
- [ ] some degrees don't show correct start / end dates. current logic may be too manual, can we link degrees to study modules in some better way?

**Comment by otahontas** [comment]
actually previous fix wasn't working: if running updater fails, any studyrights won't get added to sis-oodikone-db. Fix this

**Comment by otahontas** [comment]
Closing this in favor of more spesific #2619
