### ISSUE TITLE
fix studyright startdate / studystartdate in frontend

### ISSUE THREAD

**Issue by otahontas** [UniversityOfHelsinkiCS/oodikone#2712]
![image](https://user-images.githubusercontent.com/43019238/111663720-beb49e00-8819-11eb-8272-00c68ec2a5e7.png)

student 014317611 shows wrong start and enddates for two master programmes. start and enddates are correct in doo-oodi / oodi-oodikone db.

**Comment by otahontas** [comment]
dates in doo-oodi:
- first: 18.12.2020 - 31.07.2021
- second / fourth: 31.07.2013 - 30.07.2014
- third: 31.07.2014 - 01.09.2015

but check if these match with data coming from backend. If not, this is not just a front issue, but rather updater fakap

**Comment by Sendouc** [comment]
This is also broken on the courses of population page (noticeable when you check the Age stats at the start of the study)

Logic has been copied from the SQL query. Problem could be in either:

1) Source data
2) Logic of deciding the end date (possible since it could have easily gone unnoticed)
3) Frontend bug

It's something I tried fixing several times now and I'm fairly (but not 100% of course) sure the logic matches that of backend now. If we can rule out it's not 1) then probably a deeper dive is required to decide how the end date should actually be calculated. It would be the best if the backend just returns some `actual_start_date & actual_end_date` the front can use.

**Comment by Sendouc** [comment]
#2530 this is the root issue that might be related but it has been patched several times after that in various places.
