### ISSUE TITLE
implement Date of Course Credits -filter properly

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone#3278]
- [ ] add this filter to study programme
- [ ] implement it properly (now it does not refresh the population)

![image](https://user-images.githubusercontent.com/523235/139200202-817e40d0-5cd3-478a-9269-4dfe956d1312.png)

**Comment by dogamak** [comment]
Implemented in https://github.com/UniversityOfHelsinkiCS/oodikone/commit/863e84e2265d0df1afa5ee770549849378e2ab6c. Refreshing issue fixed with https://github.com/UniversityOfHelsinkiCS/oodikone/commit/0ce965abe3b14e455fd872b09062af1e1042143a and https://github.com/UniversityOfHelsinkiCS/oodikone/commit/c11f5d78bad1c4c67d153a1929dafdd3faf1f03b.
